# Classes exercises configuration
---
classes:
  # `class_id` is optional for configurations
  # with only one class per repository
  - class_id: "<your_class_id>"
    exercises:
      # `file` is relative to .strigo directory
      - file: "../hello-world/hello.md"
        title: "Hello!"
      - file: "../hello-world/world.md"
        title: "World!"
  - class_id: "<your_class_id>"
    exercises:
      # `syntax` is optional
      # can be "md" | "rst" | "adoc"
      # uses file extension as fallback
      - file: "../markup-syntaxes/markdown.md"
        syntax: "md"
        title: "Markdown!"
      - file: "../markup-syntaxes/restructured.rst"
        syntax: "rst"
        title: "Restructed"
      - file: "../markup-syntaxes/asciidoc.adoc"
        syntax: "adoc"
        title: "ASCII doc"
