# Classes exercises configuration
---
classes:
  - class_id: <your_class_id>
    exercises:
      # `file` can be relative or absolute
      - file: "../hello-world/hello.md"
      - file: "../hello-world/world.md"
